{
 "title": "Monitor Services",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{job!=\"router\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   },
   {
    "name": "node2",
    "label": "Instance2",
    "query": {
     "query": "label_values(cadvisor_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"localhost:9090\",job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "In-Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_chunks" }
   ]
  },
  {
   "title": "In-Memory Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_user_seconds_total{container_label_org_label_schema_group=\"monitoring\"}[1m]) * 100  / scalar(count(node_cpu_seconds_total{mode=\"user\",instance=\"$node\",job=\"$job\"})))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Prometheus Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_max_fds{job=\"prometheus\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "process_open_fds{job=\"prometheus\"}",
       "legendFormat": "Open"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "RSS"
      },
      {
       "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
       "legendFormat": "Target heap size"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"prometheus\"}",
       "legendFormat": "Next GC"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "Allocations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[1m])",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "Head Time series",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "Time series" }
     ]
    },
    {
     "title": "Head Active Appenders",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders",
       "legendFormat": "Head Appenders"
      }
     ]
    },
    {
     "title": "Samples Appended",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total[1m])",
       "legendFormat": "Samples"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "Chunks" }
     ]
    },
    {
     "title": "Head Chunks Created",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total[1m])",
       "legendFormat": "Created"
      }
     ]
    },
    {
     "title": "Head Chunks Removed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total[1m])",
       "legendFormat": "Removed"
      }
     ]
    },
    {
     "title": "Head Time Range",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      { "expr": "prometheus_tsdb_head_min_time", "legendFormat": "Min" },
      { "expr": "time() * 1000", "legendFormat": "Now" },
      { "expr": "prometheus_tsdb_head_max_time", "legendFormat": "Max" }
     ]
    },
    {
     "title": "Head GC Time/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum[1m])",
       "legendFormat": "GC Time"
      }
     ]
    },
    {
     "title": "Blocks Loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "prometheus_tsdb_blocks_loaded", "legendFormat": "Blocks Loaded" }
     ]
    },
    {
     "title": "TSDB Reloads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_reloads_total[10m])",
       "legendFormat": "Reloads"
      }
     ]
    },
    {
     "title": "TSDB Problems",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_corruptions_total[10m])",
       "legendFormat": "WAL Corruptions"
      },
      {
       "expr": "rate(prometheus_tsdb_reloads_failures_total[10m])",
       "legendFormat": "Reload Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_head_series_not_found[10m])",
       "legendFormat": "Head Series Not Found"
      },
      {
       "expr": "rate(prometheus_tsdb_compactions_failed_total[10m])",
       "legendFormat": "Compaction Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total[10m])",
       "legendFormat": "Retention Cutoff Failures"
      }
     ]
    },
    {
     "title": "WAL Latencies",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count[1m])",
       "legendFormat": "Fsync Latency"
      },
      {
       "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count[1m])",
       "legendFormat": "Truncate Latency"
      }
     ]
    },
    {
     "title": "Compactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compactions_total[10m])",
       "legendFormat": "Compactions"
      }
     ]
    },
    {
     "title": "Compaction Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum[10m])",
       "legendFormat": "Compaction Time"
      }
     ]
    },
    {
     "title": "Retention Cutoffs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_total[10m])",
       "legendFormat": "Retention Cutoffs"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Samples",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count[10m])",
       "legendFormat": "Chunk Samples"
      }
     ]
    },
    {
     "title": "Target Scrapes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
       "legendFormat": "{{ interval }}"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
       "legendFormat": "{{quantile}} ({{interval}})"
      }
     ]
    },
    {
     "title": "HTTP requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_count[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP request latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum[1m]) / rate(prometheus_http_request_duration_seconds_count[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Time spent in HTTP requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Query engine timings",
     "type": "timeseries",
     "description": "Time spent in each mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum[1m])",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Rule group evaulation problems",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_iterations_missed_total[1m])  ",
       "legendFormat": "Rule group missed"
      },
      {
       "expr": "rate(prometheus_rule_evaluation_failures_total[1m])",
       "legendFormat": "Rule evals failed"
      }
     ]
    },
    {
     "title": "Evaluation time of rule groups",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_duration_seconds_sum[1m])",
       "legendFormat": "Rule evaluation duration"
      }
     ]
    }
   ]
  }
 ]
}